workflows:
  ios-build-demo:
    name: Build OpenIM iOS Demo IPA
    max_build_duration: 60
    environment:
      vars:
        REPO_URL: "https://github.com/guigui779/quanxianshili.git"
        BRANCH: "main"
      xcode: latest
    scripts:
      - name: Clone OpenIM Demo
        script: |
          if [ ! -d "openim-ios-demo" ]; then
            git clone $REPO_URL
          else
            cd openim-ios-demo/Example
            git checkout $BRANCH
            git pull origin $BRANCH
            cd ..
          fi

      - name: Install Pods
        script: |
          pod install --repo-update

      - name: Build and Export IPA
        script: |
          mkdir -p build

          # Archive
          xcodebuild -workspace OpenIMSDKUIKit.xcworkspace \
                     -scheme OpenIMSDKUIKit_Example \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=UA9Z6NRCL8 \
                     PROVISIONING_PROFILE_SPECIFIER="00008110-001949240CA0201E" \
                     CODE_SIGN_IDENTITY="iPhone Developer: wenqiang Luo (UA9Z6NRCL8)" \
                     archive

          # Export IPA
          xcodebuild -exportArchive \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     -exportPath ./build/export \
                     -exportOptionsPlist ./ExportOptions.plist \
                     -allowProvisioningUpdates

    artifacts:
      - openim-ios-demo/Example/build/OpenIMSDKUIKit.ipa
