workflows:
  ios-build-demo:
    name: Build OpenIM iOS Demo IPA
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        REPO_URL: "https://github.com/guigui779/quanxianshili.git"
        BRANCH: "main"
    scripts:
      - name: Clone OpenIM Demo
        script: |
          if [ ! -d "openim-ios-demo" ]; then
            git clone $REPO_URL
          else
            cd openim-ios-demo
            git checkout $BRANCH
            git pull origin $BRANCH
            cd ..
          fi

      - name: Install CocoaPods
        script: |
          cd openim-ios-demo/Example
          pod install --repo-update

      - name: Build and Export IPA
        script: |
          cd openim-ios-demo/Example
          mkdir -p build

          # Archive
          xcodebuild -workspace OpenIMSDKUIKit.xcworkspace \
                     -scheme OpenIMSDKUIKit_Example \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     CODE_SIGNING_ALLOWED=NO archive

          # Export IPA
          xcodebuild -exportArchive \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     -exportPath ./build/OpenIMSDKUIKit.ipa \
                     -exportOptionsPlist ../../ExportOptions.plist

    artifacts:
      - openim-ios-demo/Example/build/OpenIMSDKUIKit.ipa
