workflows:
  ios-build-demo:
    name: Build OpenIM iOS Demo IPA
    max_build_duration: 60
    environment:
      vars:
        DEV_TEAM: $DEV_TEAM
        DEV_CERT: $DEV_CERT
        DEV_PASSWORD: $DEV_PASSWORD
        DEV_PROFILE: $DEV_PROFILE
        PROVISIONING_PROFILE_SPECIFIER: $PROVISIONING_PROFILE_SPECIFIER
      xcode: latest
    scripts:
      - name: Setup Certificates
        script: |
          echo $DEV_CERT | base64 --decode > dev_cert.p12
          echo $DEV_PROFILE | base64 --decode > dev_profile.mobileprovision

          # Install cert in keychain
          security create-keychain -p "" build.keychain
          security import dev_cert.p12 -k build.keychain -P $DEV_PASSWORD -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security unlock-keychain -p "" build.keychain

          # Copy provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp dev_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install Pods
        script: |
          cd Example
          pod install --repo-update

      - name: Build and Export IPA
        script: |
          cd Example
          mkdir -p build
          xcodebuild -workspace OpenIMSDKUIKit.xcworkspace \
                     -scheme OpenIMSDKUIKit_Example \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     DEVELOPMENT_TEAM=$DEV_TEAM \
                     PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_SPECIFIER \
                     CODE_SIGN_IDENTITY="iPhone Developer" \
                     archive

          xcodebuild -exportArchive \
                     -archivePath ./build/OpenIMSDKUIKit.xcarchive \
                     -exportPath ./build/export \
                     -exportOptionsPlist ./ExportOptions.plist \
                     -allowProvisioningUpdates

    artifacts:
      - openim-ios-demo/Example/build/export/OpenIMSDKUIKit.ipa
